dataset:
  # mode: "train"  # no need to specify; set in DM
  seed: 0
  train_val_split: 0.9
  T_high: 32
  T_low: 8
  T_query: 16
  R_25: 6  # 6

model:
  name: "LIIFCascade"
  eps_shift: !!float 1e-6
  encoder_type: "unet"  # conv or unet
  num_conv_layers: 3
  num_cascade_times: 1
  mlp:
    # in_features: 3  # must >= 2: 1 + feature_map_dim; should be overidden by unet.out_channels + 1
    hidden_features: 32  # 128
    out_features: 2
    hidden_layers: 8  # 4
    outermost_linear: true
    sine_portion: 1.
  unet:
    spatial_dims: 3
    in_channels: 16  # the first block: 2
    out_channels: 16  # feature_map_dim, 16
    channels: [16, 32, 32]
    strides: [2, 2]
  conv:
    spatial_dims: 3
    in_channels: 16  # the first Conv block: 2
    out_channels: 16
    kernel_size: 3
    strides: 1
    norm: null
    padding: 1

training:
  diff_t_weight: 0.

optimization:
  opt_name: "Adam"
  opt_params: 
    lr: !!float 1e-4
    betas: [0.9, 0.9]
  scheduler_name: "StepLR"
  scheduler_params:
    step_size: 40
    gamma: 0.5
