dataset:
  # mode: "train"  # no need to specify; set in DM
  seed: 0
  train_val_split: 0.9
  T_high: 32
  T_low: 8
  T_query: 16
  R_25: 3  # 6

model:
  name: "VariationalNetworkUpsample"
  features: [18, 36, 72, 144, 288, 18]
  sensitivity_model_features: [8, 16, 32, 64, 128, 8]
  num_cascades: 12
  ckpt_path: "/scratch/zhexwu/ImplicitNeuralRepr/data/checkpoints/varnet_mri_reconstruction.pt"

training:
  diff_t_weight: 0.

optimization:
  opt_name: "Adam"
  opt_params: 
    lr: !!float 1e-3
    betas: [0.9, 0.9]
  scheduler_name: "ReduceOnPlateau"
  scheduler_params:  
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: !!float 1e-6
