model:
  name: "SirenComplex"
  in_features: 4
  hidden_features: 256
  out_features: 2
  hidden_layers: 12
  outermost_linear: true
  first_omega_0: 30
  hidden_omega_0: 30

transforms:
  dc:
    name: "SENSE"
    sens_type: "exp"
    num_sens: 2
    in_shape: [10, 25, 127, 127]  # (Lambda, T, H, W)
    mask_params: 
      if_temporal: true
    seed: 0

  reg:
    name: "FiniteDiff"
    dim: -1  # (B, T), TVt

  reg_profile:
    name: "log"
    profile_params:
      alpha: !!float 5

optimization:
  siren:
    opt_name: "AdamW"
    opt_params: 
      lr: !!float 1e-3
    scheduler_name: "StepLR"
    scheduler_params:
      step_size: 20
      gamma: 0.5
  