dataset:
  # mode: "train"  # no need to specify; set in DM
  res: 127
  T: 25
  num_sens: 2
  seed: 0
  train_val_split: 0.9

model:
  name: "LIIFParametric3DConv"
  eps_shift: !!float 1e-6
  mlp:
    # in_features: 3  # must >= 2: 1 + feature_map_dim; should be overidden by unet.out_channels + 1
    hidden_features: 128
    out_features: 2
    hidden_layers: 4
    outermost_linear: true
    sine_portion: 1.
  unet:
    spatial_dims: 3
    in_channels: 2
    out_channels: 8  # feature_map_dim
    channels: [32, 64]
    strides: [2]

# transforms:
#   dc:
#     name: "SENSE"
#     sens_type: "exp"
#     num_sens: 2
#     in_shape: [25, 128, 128]
#     mask_params: 
#       sw: 0.15
#       sm: 0.7
#       sa: 0.057535
#       if_temporal: true
#     seed: 0

optimization:
  opt_name: "AdamW"
  opt_params: 
    lr: !!float 1e-4
  scheduler_name: "StepLR"
  scheduler_params:
    step_size: 10
    gamma: 0.5
