dataset:
  seed: 0
  train_test_split: 0.9

model:
  name: "LIIFParametricComplexSiren"
  # mlp:
  #   # in_features: 3  # must >= 2: 1 + feature_map_dim; should be overidden by unet.out_channels + 1
  #   hidden_features: 256
  #   out_features: 1
  #   hidden_layers: 5
  mlp:
    # in_features: 3  # must >= 2: 1 + feature_map_dim; should be overidden by unet.out_channels + 1
    hidden_features: 128
    out_features: 2
    hidden_layers: 4
    outermost_linear: true
    sine_portion: 1.
  unet:
    spatial_dims: 2
    in_channels: 50
    out_channels: 8  # feature_map_dim
    channels: [32, 64]
    strides: [2]

transforms:
  dc:
    name: "SENSE"
    sens_type: "exp"
    num_sens: 2
    in_shape: [25, 128, 128]
    mask_params: 
      if_temporal: true
    seed: 0

optimization:
  opt_name: "AdamW"
  opt_params: 
    lr: !!float 1e-3
  scheduler_name: "StepLR"
  scheduler_params:
    step_size: 10
    gamma: 0.5
