model:
  name: "SirenComplex"
  in_features: 3
  hidden_features: 256
  out_features: 2
  hidden_layers: 16
  outermost_linear: true
  first_omega_0: 30
  hidden_omega_0: 30

transforms:
  dc:
    name: "SENSE"
    sens_type: "exp"
    num_sens: 2
    in_shape: [25, 127, 127]
    mask_params: 
      if_temporal: true
    seed: 0

  reg:
    name: "FiniteDiff"
    dim: -1  # (B, T), TVt

optimization:
  siren:
    opt_name: "AdamW"
    opt_params: 
      lr: !!float 1e-4
    scheduler_name: "StepLR"
    scheduler_params:
      step_size: 50
      gamma: 0.5
  grid_sample:
    opt_name: "AdamW"
    opt_params: 
      lr: !!float 5e-3
    scheduler_name: "StepLR"
    scheduler_params:
      step_size: 1000
      gamma: 0.5
  