dataset:
  seed: 0
  train_test_split: 0.9

model:
  name: "LIIFNonParametric"
  mlp:
    num_heads: 4  # split into num_heads layers
  unet:
    spatial_dims: 2
    in_channels: 25
    out_channels: 2304  # feature_map_dim
    channels: [128, 512, 2304]
    strides: [2, 2, 2]

transforms:
  dc:
    name: "SENSE"
    sens_type: "exp"
    num_sens: 2
    in_shape: [25, 128, 128]
    mask_params: 
      if_temporal: true
    seed: 0

optimization:
  opt_name: "AdamW"
  opt_params: 
    lr: !!float 1e-5
  scheduler_name: "StepLR"
  scheduler_params:
    step_size: 10
    gamma: 0.5
